version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
            - mongodb
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_DATABASE: '${DB_DATABASE:-incident_logger}'
            MYSQL_USER: '${DB_USERNAME:-sail}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
    mongodb:
        image: 'mongo:7'
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME:-root}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD:-password}'
            MONGO_INITDB_DATABASE: '${MONGO_DATABASE:-incident_logger}'
        volumes:
            - 'sail-mongodb:/data/db'
volumes:
    sail-mysql:
        driver: local
    sail-mongodb:
        driver: local
