services:
    laravel.test:
        container_name: il-api
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mongodb

    laravel-worker:
        container_name: il-worker
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        depends_on:
            - laravel.test
            - mongodb
        volumes:
            - '.:/var/www/html'
        entrypoint: ["php", "artisan", "queue:work", "--queue=high,medium,low"]
        restart: unless-stopped

    mongodb:
        container_name: il-db
        image: 'mongo:7'
        ports:
            - '${MONGO_PORT}:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME:-root}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD:-password}'
            MONGO_INITDB_DATABASE: '${MONGO_DATABASE:-incident_logger}'
        volumes:
            - 'sail-mongodb:/data/db'
volumes:
    sail-mysql:
        driver: local
    sail-mongodb:
        driver: local
